// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinecraftSpy;

#nullable disable

namespace MinecraftSpy.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MinecraftSpy.Subscription", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<ulong>("ChannelID")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by");

                    b.Property<ulong>("MessageID")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("message_id");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("server_address");

                    b.Property<short>("ServerPort")
                        .HasColumnType("smallint")
                        .HasColumnName("server_port");

                    b.HasKey("ID");

                    b.ToTable("subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
